### ISSUE TITLE
Projection Matrix

### ISSUE THREAD

**Issue by fedeface98** [arcadelab/deepdrr#105]
Hello, 

I'm trying to get the projection matrix carm.get_camera_projection() but I obtained strange results: 

[[      0.           -5255.0195         786.34827    1023886.44      ]
 [   5257.732            2.6808205      767.99536     708424.94      ]
 [      0.               0.00349065       0.9999939      819.7382    ]]

Why the number inside the matrix are not between 0 and 1?

There is a way to obtain separately the instrinsic and the extrinsic matrix?

Thanks a lot

**Comment by benjamindkilleen** [comment]
The CameraProjection contains these as elements, so you can do `carm.index_from_world.intrinsic` and `carm.index_from_world.extrinsic`

`index_from_world` is an alias for `get_camera_projection()`
