### ISSUE TITLE
FLIP AXIS

### ISSUE THREAD

**Issue by fedeface98** [arcadelab/deepdrr#106]
Hello, I had the same issue and I fixed it by using np.fliplr. But in this way the projection matrix remain the same, so my question is if there are some parameters to set in the code to avoid this situation and obtain the correct projection matrix?

_Originally posted by @fedeface98 in https://github.com/arcadelab/deepdrr/issues/99#issuecomment-1812538022_

**Comment by benjamindkilleen** [comment]
We haven't added this as a built-in function, but you can do something like
```
w = index_from_world.intrinsic.sensor_width
flipped_index_from_index = geo.FrameTransform(
    np.array(
        [
            [-1, 0, w - 1],
            [0, 1, 0],
            [0, 0, 1],
        ]
    )
)
index_from_world = flipped_index_from_index @ index_from_world
```

**Comment by fedeface98** [comment]
I am sorry but I think the problem in my projection matrix is not the x axis flipped but about the rotation angles. I explain better:

I rotate the C-Arm with: carm.move_to(alpha=13.8, beta=-23.5,degrees=True)

When I look the  'carm.index_from_world.extrinsic' and I extract the rotation matrix, it seems to be obtained from the opposite angles (alpha=-13.8, beta=23.5 and not alpha=13.8, beta=-23.5 set in 'carm.move_to' ).

In particular I used the following lines to obtain the angles:

r = Rotation.from_matrix(carm.index_from_world.extrinsic[0:3,0:3])
angles = r.as_euler("xyz",degrees=True)

I missed something that I have to set in the carm initialization to rotate with the angles that I want?
