### ISSUE TITLE
How  to set up a simulation of an  orthogonal projection?

### ISSUE THREAD

**Issue by sawwhite** [arcadelab/deepdrr#108]
I need to simulate an EOS, which means an X-ray tube at an infinite distance. Do you have any suggestions on how to achieve this functionality?

**Comment by benjamindkilleen** [comment]
You would have to rewrite project_kernel.cu. We don't support orthogonal projection at this time, but it wouldn't be hard to set up on your own.

Instead of a projection matrix, you just need a frame transform matrix.
