### ISSUE TITLE
Isocenter / origin question

### ISSUE THREAD

**Issue by fedeface98** [arcadelab/deepdrr#109]
Hello,

I have a doubt about the setting of the isocenter and the translations. For example, If i set the isocenter of the Carm in the following way: carm.move_to(isocenter_in_world =  ct.center_in_world + geo.v(0,0,0))
Is it correct that I put the isocenter of the Carm in the center of the ct volume and with the term 'geo.v(0,0,0)' I am modeling the translation around the center of the ct volume? Could we see this translation as the translation between the center of the CT and the center of the generated fluoroscopy?

Thanks a lot

**Comment by benjamindkilleen** [comment]
The isocenter is the center of rotation of the C-arm. In many cases, this happens to correspond to the imaging center between the X-ray source and the detector center, but not necessarily. If you use the default settings for `MobileCArm`, then it should be the case.
