### ISSUE TITLE
About the number of supported materials

### ISSUE THREAD

**Issue by PluvioStephan** [arcadelab/deepdrr#131]
Hello,

I was wondering why the code only supports up to 14 materials at the moment? I am planning to extend the code to support more, do you think, there could be any issues with that?

Cheers,
Pluvio

**Comment by benjamindkilleen** [comment]
We've found the materials supported to be sufficient for most users, but you are free to add more! If you would like, you can open a pull request with the material coefficients added and some sanity checks.

**Comment by PluvioStephan** [comment]
Thanks, I'll see what I can do! :)
