### ISSUE TITLE
Is there any parameters about the distance between object and source?

### ISSUE THREAD

**Issue by minjoony** [arcadelab/deepdrr#27]
Hi, I wonder that there is any parameters about the distance between object and source,
which means the red line on the below figure.

![image](https://user-images.githubusercontent.com/48172859/109127993-5e8a8900-7792-11eb-952c-cfc31d07f130.png)

Also, How can I get the forward-projection results on the `v1.0.1-alpha` branch?
On `master`, I wrote below codes on `mass-attenuation.py`
![image](https://user-images.githubusercontent.com/48172859/109127661-05225a00-7792-11eb-9d6c-9ece733f2842.png)

Then, I could get below forward-projection results.
![image](https://user-images.githubusercontent.com/48172859/109128456-dd7fc180-7792-11eb-86b0-89122b317fc9.png)

However, On `v1.0.1-alpha`, I couldn't find the right spot to insert my codes to get forward-projection results.

Thanks for your valuable research again.

**Comment by maxrohleder** [comment]
Hey @artiiicy! Assuming, that the volume you want to project is in the center of rotation of the simulated C-Arm, the parameter you are looking for is the `isocenter_distance`. You can find it in action in the example in line 60:

```python
# defines the C-Arm device, which is a convenience class for positioning the Camera.
carm = CArm(
    isocenter=geo.point(0, 0, 0),
    isocenter_distance=800,
)
```

Hope that answers at least the first of your questions.
Cheers, 
Max

**Comment by benjamindkilleen** [comment]
See also `deepdrr.SimpleDevice.align()`
