### ISSUE TITLE
Pretreined model weights

### ISSUE THREAD

**Issue by luantunez** [arcadelab/deepdrr#42]
Hello and thank you for a great library!
Where can I find  the weights for the pretrained model?
Lucia

**Comment by mathiasunberath** [comment]
Have you tried": https://github.com/arcadelab/deepdrr/blob/caf97a1e6bb64d6791baafef26e248a2ca540d59/deepdrr/segmentation.py#L14 ?

**Comment by benjamindkilleen** [comment]
If you are using a recent version (>1.0), these weights should download automatically.
