### ISSUE TITLE
Questions regarding the article

### ISSUE THREAD

**Issue by tomeramit** [arcadelab/deepdrr#43]
Hi guys,

I was wondering how you combine those 3 parts (attenuation, scatter, noise) can you elaborate on that?
also when playing with the projection I saw that the output xray is somehow normalized between 0 and 1, can you elaborate on that as well?

btw very nice article and project!
Thanks

**Comment by mathiasunberath** [comment]
Photon signal and scatter are additive and noise is computed based on that signal (both Poisson noise and correlated noise to simulate detector readout).  You can find those in https://github.com/arcadelab/deepdrr/blob/main/deepdrr/projector/projector.py#L577 and https://github.com/arcadelab/deepdrr/blob/main/deepdrr/projector/projector.py#L591.

The signal that we simulate may be within 0,1 but there is no guarantee. We do not specifically simulate I(x)/I_0, so you cannot assume [0,1].

**Comment by tomeramit** [comment]
Thanks!
