### ISSUE TITLE
ValueError on example_projector !?

### ISSUE THREAD

**Issue by fselka** [arcadelab/deepdrr#53]
Hi by running the example_projector.py I had this error: 
 File "/deepdrr/deepdrr/projector/projector.py", line 462, in project ijk_from_world @ world_from_index,
**ValueError:** matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4). 
Any clues ?

**Comment by benjamindkilleen** [comment]
@maxrohleder I believe this something you were working on?

**Comment by benjamindkilleen** [comment]
The example projector script has now been simplified and corrected. It should run smoothly.
