### ISSUE TITLE
Projection of 3D masks

### ISSUE THREAD

**Issue by fselka** [arcadelab/deepdrr#54]
Given a 3D segmentation of 3D CT can we project the 3D segmentation in order to get a 2D image (2D masks) ?

**Comment by benjamindkilleen** [comment]
Thanks for your interest! There isn't a built-in way to do this right now, as it's a use-case we just haven't needed for ourselves yet. While we expect to add it at some point in the future, there are currently higher priority items.

**Comment by findme8** [comment]
@fselka @benjamindkilleen hey, thanks for the question and answer! May I ask that how I could generate the 3D segmentation of 3D CT scan? any code or software recommendations? Thank you so much!

**Comment by fedeface98** [comment]
Is it possible to use directly the deepDRR projector.py to project 3D mask in 2D?

**Comment by benjamindkilleen** [comment]
See #89

**Comment by fedeface98** [comment]
Sorry but in #89 they were talking about HU, not projecting a 3d
segmentation in 2D.

Il giorno mer 6 dic 2023 alle 18:38 Benjamin D. Killeen <
***@***.***> ha scritto:
