### ISSUE TITLE
Project with coronal view

### ISSUE THREAD

**Issue by junjun1023** [arcadelab/deepdrr#59]
Hi, I'm trying to create DRRs with coronal view. I converted dicom to nifti format and create ```Volume``` as instructions. However, I tried many different rotations with ```volume.rotate```, the result is not as expectations. And I'm confused why the the size of dicom which is ```(512, 512)``` before projection changed after projection?

**Comment by benjamindkilleen** [comment]
Do you have a minimal code example?

**Comment by benjamindkilleen** [comment]
(Closing was accidental)

**Comment by junjun1023** [comment]
@benjamindkilleen 

```python

import dicom2nifti
# convert dicom to nifti
dicom2nifti.convert_directory(path_of_dicom_dir, filepath)

# The code below is from deepdrr_demo.ipynb
volume = Volume.from_nifti(filepath)
carm = deepdrr.MobileCArm(isocenter=volume.center_in_world, alpha=0, beta=0, degrees=True, min_alpha=-40, max_alpha=40, min_beta=0, max_beta=20)

with deepdrr.Projector(
    volume=volume,
    carm=carm,
    step=0.1,  # stepsize along projection ray, measured in voxels
    mode="linear",
    max_block_index=200,
    spectrum="90KV_AL40",
    photon_count=100000,
    add_scatter=False,
    threads=8,
    neglog=True,
) as projector:
    image = projector.project()
    plt.imshow(image, cmap='gray')
    plt.show()
```

![image](https://user-images.githubusercontent.com/44397290/135370255-414b0940-f215-40ba-9d92-e2b8b99b60a6.png)

**Comment by junjun1023** [comment]
I can't tell what projection plane the result is.

**Comment by benjamindkilleen** [comment]
The latest pre-release includes some convenience functions to handle the rotations, assuming their anatomical coordinate spaces are correct. I believe the following should work.

After positioning the volume faceup or facedown, I suggest rotating the simulated C-arm by changing alpha/beta. This may not be how a cranial X-ray is normally taken, but our convenience functions are designed with intraoperative procedures in mind, so there is more support. You can of course pass in the camera matrix yourself instead of the C-arm object.

```Python
import dicom2nifti
# convert dicom to nifti
dicom2nifti.convert_directory(path_of_dicom_dir, filepath)

volume = Volume.from_nifti(filepath)
volume.faceup() # Available in latest pre-release
carm = deepdrr.MobileCArm(isocenter=volume.center_in_world)
carm.move_to(alpha=0, beta=0, degrees=True) # Can also be done in the with block

# Extra args have reasonable defaults.
with deepdrr.Projector(volume, carm=carm) as projector:
    image = projector.project()
    plt.imshow(image, cmap='gray')
    plt.show()
```

**Comment by junjun1023** [comment]
@benjamindkilleen 
Thank you for your reply! I'm not familiar with the way to adjust a 3D image and how is C-arm work in the scene.
I have tried your sample code, and encountered error ```isocenter [173.75      14.        -7.596878   1.      ] is out of bounds. Use world_from_device transform to position the carm in the world.``` Does it mean that I need to pre-process my 3D image?

The image below is the result I read with `pydicom` and extract with different axis.
![1633004429481](https://user-images.githubusercontent.com/44397290/135454020-c1bf0183-52c4-4c59-b6cb-07ee2f9a4112.jpeg)

**Comment by benjamindkilleen** [comment]
Ah, that is my mistake. I have edited the excerpt to omit the isocenter keyword, which does something slightly different.

**Comment by junjun1023** [comment]
@benjamindkilleen
The result looks quite different from the single slice of AP view above. It seems like a patch of whole lung view.
Do you have any suggestion to get the whole PA view like the image of README?

![1633012172176](https://user-images.githubusercontent.com/44397290/135475454-9be56cb6-1bd3-4c0d-b673-39766d199318.jpg)

**Comment by benjamindkilleen** [comment]
@junjun1023 You will have to translate the isocenter (which, by default, is on the principle ray), to be where you want in the anatomy. I assumed that was the center, but you may want to move the camera closer or further away. You can do this by translating the volume or repositioning the C-arm with built-in functions. You can also adjust the camera parameters passed to the C-arm class to change the magnification.

You may find the built-in visualization tools to be useful. The following will open an interactive VTK window with the C-arm and volume shown. This may help understand the geometry setup, so you can tinker with it.

```Python
from deepdrr import vis

...

vis.show(volume, carm, full=True)
```

**Comment by junjun1023** [comment]
@benjamindkilleen 

Excuse me, is there any way to convert a 3D ```numpy.array``` to ```Volume```? I saw that there are some parameters need to pass e.g. material, but I don't know what should be passed. What I want to do is to create subvolumes and project the subvolumes with ```Projector```.

**Comment by junjun1023** [comment]
I can get the whole PA view of projection by setting ```source_to_isocenter_vertical_distance``` larger than default value. Thank you for helping.

**Comment by benjamindkilleen** [comment]
That would work. You can do the numpy conversion with the class constructor itself or the `from_hu()` method.
