### ISSUE TITLE
dicom convert nii

### ISSUE THREAD

**Issue by Floyd809** [arcadelab/deepdrr#64]
Hi,
  Is there a scirpt which can transfrom dicom to nii in this  project?

**Comment by benjamindkilleen** [comment]
The existing tool, dcm2niix, is very mature and reliable. I recommend using that: https://github.com/rordenlab/dcm2niix

**Comment by Floyd809** [comment]
> The existing tool, dcm2niix, is very mature and reliable. I recommend using that: https://github.com/rordenlab/dcm2niix

Thank you for your suggestion !
