### ISSUE TITLE
"Simulate scatter" function always returns zero scatter intensity

### ISSUE THREAD

**Issue by Xingorno** [arcadelab/deepdrr#81]
Thank you for your great job!

I am running the latest released version (v1.1.1). When I tested the scatter function (using "test_scatter.py and geometry_testing.py"), I found that it didn't work.  The output of the scatter intensity was an all-zero array after running the "scatter_kernel.cu", and the outputs of "hits_scatter" and "hits_primary" are zero as well.  I have no idea about this issue. Can you help me with this? Any advice is appreciated! 

Thanks in advance!

**Comment by mathiasunberath** [comment]
Based on your description it's difficult to guess what may be going on. However, I'd generally be cautious with scatter use right now. We've found that (depending on the application) it's not really necessary and is much less developed compared to the rest of the framework. We have a .ore sophisticated scatter simulation competed but have not been able to merge it yet. Timeline unclear.

**Comment by Xingorno** [comment]
Thank you so much for your quick response! And I have also checked some previously posted issues in this channel.  I basically have a good understanding of the scatter simulation in the DeepDRR framework.  As you suggested, an X-ray without scatter is good enough for me now. Really appreciate!
