### ISSUE TITLE
About DRR Image

### ISSUE THREAD

**Issue by fanyigao** [arcadelab/deepdrr#87]
your work is brilliant! But why I get a drr image like this，so cluttered？ and I can get a more 'proper' drr by ITK.
![image](https://github.com/arcadelab/deepdrr/assets/105158872/0b994446-d480-45e7-9654-968828db9f06)

**Comment by mathiasunberath** [comment]
I think you are referring to the bowel. This to me suggests that the CT you are using for simulation either has air in the bowel or the bowel has been incorrectly segmented. Both of these issues are not as prominent if you use a standard (single material single energy) projector like the one in ITK.

**Comment by mathiasunberath** [comment]
If you have specific questions, we can try and help answer.

**Comment by fanyigao** [comment]
> 

Hello！How to generate drrs which only have bone, I notice deepdrr use three types of image to generate one drr, and I want to only project the bone.

**Comment by fanyigao** [comment]
> 如果您有具体问题，我们可以尝试帮助解答。

Hello！How to generate drrs which only have bone, I notice deepdrr use three types of image to generate one drr, and I want to only project the bone.

**Comment by benjamindkilleen** [comment]
Pass your binary bone segmentation to `deepdrr.Volume.from_nifti` with `segmentation=True` and then proceed as usual.

**Comment by fanyigao** [comment]
thank you for your help!
