### ISSUE TITLE
gpu utilization and performances

### ISSUE THREAD

**Issue by WilsonFok2020** [arcadelab/deepdrr#88]
Thank you very much for creating this python module for radiographs and fluoroscopy.

My question is related to speeding up the calculation of the projection on gpu and the data transfer between device/ gpu and host/ python. 

To profile the gpu performance, I have deployed Nsight system and Nsight compute in Nvidia CUDA toolkit.

Nsight system identifies that the program spends almost equal amount of time on the data transfer from device to host and on projection kernel. 
More precisely, I performed a simple experiment. The experiment has 3 cases. Case 1: project and then transfer a single array. Case 2: project and transfer 2 arrays, thereby doubling the amount of data that has to be transferred. Case 3: project but no transfer at all.

While case 3 shows that no time is spent on data transfer, what is surprising to me is that the transfer time for case 1 and 2 is very similar.

**Is there a solution to reduce this overhead?**

Nsight compute suggests that the program has a bottleneck at the gpu L2  to L1 cache memory.
Both hit rates exceed 90%.
Shared memory has hardly been used, if at all.
While the memory usage is very high, the SM usage is rather low, < 20%.
This combination of signals appears to be telling me the threads are siting idle and are waiting for the data to come through or to be written.

**Is there a better way to utilize the gpu memory and consequently the threads?**

My programming experience is mainly in Python. 
**I greatly appreciate if you can point me to some resources on CUDA + pycuda that can address the above bottlenecks.** 

Thanks

**Comment by benjamindkilleen** [comment]
Hi @WilsonFok2020, thank you for your interest in DeepDRR! When designing DeepDRR, we envisioned a specific use case, where repeated projections calls are applied to the same volumes, with only the relative poses among volumes and the camera differing between calls. Perhaps I misunderstand what you mean by "array transfer." At initialization of the Projector, all volume data arrays are transferred to the device. At projection time, when the kernel is called, 2D image data are transferred back. If by "array transfer" you mean the initialization, then your cases seem to omit the intended use-case, where initialization happens once, and projection occurs many hundreds or thousands of times.

I am not surprised that cache hits are high but SM usage is low. Threads for adjacent rays in the projector will access contiguous memory in the CUDA textures, but for most camera geometries, the projection will only require a pyramidal portion of the volume, ignoring the rest.

You can consider cropping your volumes to the required portion if you want to improve SM utilization, but this will only speed up the initialization and reduce memory, not improve the repeated projection operation.

**Comment by WilsonFok2020** [comment]
@benjamindkilleen Like your description above, what I intend to do is to project various images of an identical volume from different camera poses.
However, I would like to speed up the computation of the projection.



What Nsight system has observed is that the program spends much time at memcpy dtoh operation (note:  transfer data from host to device needs far less time). To explore what is going on, I performed the aforementioned experiment with the 3 cases. What I am trying to figure out is whether the transfer of data from device to host is really caused by the 2D image array. Case 1 transfers only the 2D intensity array. Case 2 transfers photon and intensity arrays. Case 3 transfers nothing. 
Hence, I can directly observe which part of the code is calling  memcpy dtoh. It turns out, surprisingly, that the time taken for the transfer is not proportional to the amount of data. Time taken for case 1 is almost the same as case 2. 

Regarding to shared memory, I have come across [this document ](https://documents.pub/document/introduction-to-nvidia-profiling-tools-introduction-to-nvidia-profiling-tools-2.html?page=61) Page 60-67 illustrate the use of shared memory and synchronization to speed up the computation. 
Have you explored their optimization trick before? Does it work?

**Comment by WilsonFok2020** [comment]
@benjamindkilleen 
Upon further investigation, it is clear to me now that the bottleneck lies at the capacity of memory throughput. The path down shared memory is useful purely for my understanding of gpu, not for resolving the speed problem. 

Whenever we reach a memory throughput of 99%, the SM stalls at around 24%. 

How can we reduce the memory throughput?
Is it practical to use half / float16 datatype for the texture arrays, instead of single precision / float32?
Would this choice theoretically double the capacity of memory throughput?

Thanks

**Comment by WilsonFok2020** [comment]
After a series of trials and errors, it has become obvious to me that the performance bottleneck resides at the rate of reading global memory or texture array. 
It is incorrect to believe that float 16 could speed up memory transfer, even though we are transferring less data. Converting a float 32 to float 16 reduces the rate of transfer by half. Thus, all in all, the overall speed remains the same.

**Comment by mathiasunberath** [comment]
Thanks. We'll be releasing a new version that uses new texture classes as the ones we currently use are deprecated. It's possible that this will affect your issue as well, so keep an eye out.
