### ISSUE TITLE
DRR is white.

### ISSUE THREAD

**Issue by BraveDistribution** [arcadelab/deepdrr#89]
Hello,

Thank you for the amazing open-sourced work. I have tried an example with the pelvis dataset and it worked flawlessly, however after changing to my own data (chestCT), it failed to output anything. The whole DRR has white rectangle. 
![image](https://github.com/arcadelab/deepdrr/assets/36101458/de3a1003-363b-4757-8311-69309652f579)

Unfortunately, I cannot share the data I have due to privacy reasons. Could you point me in the right direction how to debug this?
The code is as follows:
```
vol_path = "/results/***/database_ct_heart/{}/zpat{}reg-tp0.nii".format(vol_id, vol_id)
volume = Volume.from_nifti(vol_path, use_thresholding=True)
volume.faceup()
carm = MobileCArm()
print('Volume origin ', volume.origin)
print('Volume origin in anatomical ', volume.origin_in_anatomical)
print('Volume origin in world ', volume.origin_in_world)
print('Volume center in world ', volume.center_in_world)
print('Volume ijk', volume.world_from_ijk)
print('Volume spacing: ', volume.spacing)

with Projector(
    volume=volume,
    carm=carm,
    step=0.1,  # stepsize along projection ray, measured in voxels
    spectrum="90KV_AL40", # energy spectrum
    photon_count=100000, # number of photons to simulate
    # scatter_num=5, # number of scatter events to simulate
    neglog=True, # apply negative log transform to image (convenient for visualization)
    intensity_upper_bound=4, # Adjust for better visualization
) as projector:
    carm.move_to(isocenter_in_world=volume.center_in_world + geo.v(0, 0, -300), alpha=0, beta=0, gamma=0, degrees=True)
    image = projector.project()
    print(np.unique(image))
    # tr = transforms.Affine2D().rotate_deg(90)
    plt.imshow(image, cmap="gray")
    plt.axis('off')
    # display(Image.fromarray((image * 255).astype(np.uint8)))
```

I tried also to vizualise geometry:
![image](https://github.com/arcadelab/deepdrr/assets/36101458/a8254a4f-6714-4363-9254-ca70bbc3dcb8)

If I move the carm to the (-200, -200, -200) - the output is only black image. 

The values of the volume:
volume min:  1.0279601
volume max:  1.0336576

thanks

**Comment by mathiasunberath** [comment]
It would also make sense to visualize detector size so that you could estimate whether the white box you see there is in fact all of your volume, which I believe it is. 
You can check this, for example, by window leveling the projection aggressively to reveal details in the white area. 
Another reason (and this may happen regardless of the first) is that you are now using your own data. Make sure it's read in correctly (HU values, volume dimensions, etc.).

**Comment by BraveDistribution** [comment]
Would you be so kind to elaborate a bit more?

How can I try the window leveling approach?

Another reason (and this may happen regardless of the first) is that you are now using your own data. Make sure it's read in correctly (HU values, volume dimensions, etc.).

I think they are loaded correctly.
![image](https://github.com/arcadelab/deepdrr/assets/36101458/22274a71-473b-47bd-af98-c343d56544be)

Since I have the volume range as:
volume min: 1.0279601
volume max: 1.0336576

Do you think the problem might be with HU values?

**Comment by BraveDistribution** [comment]
Thanks.

![image](https://github.com/arcadelab/deepdrr/assets/36101458/0dbf8aae-5a29-4d03-af1e-8b44ca2b3f05)

![Uploading image.png…]()

Sorry, max/min is -1.98 to 6.21 accoridng to slicer. Could you elaborate what kind of values the DeepDRR expects?

**Comment by BraveDistribution** [comment]
Actually, the dataset is publicly available at: https://figshare.com/articles/dataset/cardiac_ct_data_15sets/1379059?file=3322286
